In [164]:
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

import glob
import os
import os.path as osp
import shutil
import random
import math
import json
from PIL import Image
from tqdm import tqdm

import torch
import torch.nn as nn
import torch.optim as optim
import torch.utils.data as data
import torchvision
from torchvision import models, transforms

In [165]:
class_index = ['コンクリート', 'レール',  '背景あり', '金枠あり']
weight_index = [0, 0, 0, 0]
batch_size = 32

データの前処理

In [166]:
class makeDataList():
    def __init__(self):
        self.rootpath =  './ImageData/'
        # 10枚に１枚が検証用データ
        self.trainPer = 10
    
    def shuffle_train_test(self):
        for path in glob.glob(self.rootpath+'/*'):
            print(path)

            trainpath = './train/'+path.split('/')[2]
            if not os.path.exists(trainpath):
                os.makedirs(trainpath)

            valpath = './val/'+path.split('/')[2]
            if not os.path.exists(valpath):
                os.makedirs(valpath)

            for j,image in enumerate(glob.glob(self.rootpath+path.split('/')[2]+'/*.jpg')):
                print(j)
                if j%self.trainPer==0:
                    shutil.copyfile(image, './val/'+path.split('/')[2]+'/'+image.split('/')[3])
                else:
                    shutil.copyfile(image, './train/'+path.split('/')[2]+'/'+image.split('/')[3])
                    
    def make_data_path(self, phase='train'):
        target_path = osp.join('./'+phase+'/**/*.jpg')
        path_list = []
        for path in glob.glob(target_path):
            path_list.append(path)
        
        return path_list

In [167]:
class BaseTransform():
    def __init__(self):
        self.size = 256
        self.mean = ((0.5,))
        self.std = ((0.22,))
        self.base_transform = {
            'train':
                transforms.Compose([
                transforms.RandomResizedCrop(self.size, scale=(0.5,1.0)),
                transforms.RandomHorizontalFlip(),
                transforms.ToTensor(),
                transforms.Normalize(self.mean, self.std)
                ]),
            'val':
                transforms.Compose([
                transforms.Resize(self.size),
                transforms.CenterCrop(self.size),
                transforms.ToTensor(),
                transforms.Normalize(self.mean, self.std)
                ])
        }
        
    def __call__(self, img, phase='train'):
        return self.base_transform[phase](img)

In [168]:
class HymenopteraDataset(data.Dataset):
    
    def __init__(self, file_list, transform=None, phase='train'):
        self.file_list = file_list
        self.transform = transform
        self.phase = phase
        
    def __len__(self):
        return len(self.file_list)
    
    def __getitem__(self, index):
        img_path = self.file_list[index]
        img = Image.open(img_path)
        img_transformed = self.transform(img, self.phase)
        if self.phase == 'train':
            label = img_path.split('/')[2]
            label = class_index.index(label)
        elif self.phase == 'val':
            label = img_path.split('/')[2]
            label = class_index.index(label)
        
        return img_transformed, label

In [169]:
dataList = makeDataList()
#dataList.shuffle_train_test()
trainList = dataList.make_data_path(phase='train')
valList = dataList.make_data_path(phase='val')

In [170]:
trainDataset = HymenopteraDataset(file_list=trainList, transform=BaseTransform(), phase='train')
valDataset = HymenopteraDataset(file_list=valList, transform=BaseTransform(), phase='val')

In [171]:
index = 10
print(trainDataset.__getitem__(index)[0].size())
print(trainDataset.__getitem__(index)[1])

torch.Size([1, 256, 256])
0


In [172]:
for i,class_ in enumerate(class_index):
    files = glob.glob('./train/'+class_+'/*.jpg')
    weight_index[i] = len(files)
weight_index

[2459, 1375, 1891, 251]

In [173]:
trainDataloader = torch.utils.data.DataLoader(trainDataset,
                                              batch_size=batch_size,
                                              shuffle=True)
valDataloader = torch.utils.data.DataLoader(valDataset,
                                            batch_size=batch_size,
                                            shuffle=False)
dataloaders_dict = { 'train': trainDataloader, 'val': valDataloader }
batch_iterator = iter(dataloaders_dict['train'])
inputs, labels = next(batch_iterator)

print(inputs.size())
print(labels)

torch.Size([32, 1, 256, 256])
tensor([0, 0, 1, 2, 0, 0, 0, 3, 1, 0, 2, 1, 3, 0, 0, 0, 2, 0, 2, 3, 1, 1, 2, 1,
        0, 1, 0, 1, 2, 0, 1, 1])


In [174]:
new_weight_index = list(map(lambda x: float(math.ceil(sum(weight_index)/x)), weight_index))
new_weight_index  = list(map(lambda x: x/3, new_weight_index))

In [175]:
new_weight_index = [1.0, 1.7, 1.7, 8.0]

GoogLeNetを使った学習

In [176]:
class MyNet(nn.Module):
    def __init__(self):
        super(MyNet,self).__init__()
        self.conv1 = nn.Conv2d(1,32,3,1)
        self.conv2 = nn.Conv2d(32,64,3,1)
        self.pool = nn.MaxPool2d(2,2)
        self.dropout1 = nn.Dropout2d(0.25)
        self.dropout2 = nn.Dropout2d(0.5)
        self.fc1 = nn.Linear(12*12*64,128)
        self.fc2 = nn.Linear(128,10)

    def forward(self,x):
        x = self.conv1(x)
        x = f.relu(x)
        x = self.conv2(x)
        x = f.relu(x)
        x = self.pool(x)
        x = self.dropout1(x)
        x = x.view(-1,12*12*64)
        x = self.fc1(x)
        x = f.relu(x)
        x = self.dropout2(x)
        x = self.fc2(x)

        return f.log_softmax(x, dim=1)

In [181]:
class ResNet():
    
    def __init__(self):
        self.net = models.resnet18(pretrained=True)
        self.net.conv1 = nn.Conv2d(1, 64, kernel_size=7, stride=2, padding=3, bias=False)
        self.net.fc = nn.Linear(self.net.fc.in_features, len(class_index))
        self.net.train()
        self.device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
        self.net.to(self.device)
        self.num_epochs = 50
        print('use in device: ', self.device)
        print(self.net.fc.out_features)
        weights = torch.tensor(new_weight_index).cuda()
        print(weights)
        self.criterion = nn.CrossEntropyLoss(weight=weights)
        self.optimizer = optim.SGD(params=self.net.parameters(), lr=0.001, momentum=0.9)
        self.lr_scheduler = optim.lr_scheduler.StepLR(self.optimizer, step_size=7, gamma=0.1)
        self.bestAcc = 0.0
#         load_path = './weightsFineTuningColor_epoch48_0.724258.pth'
#         load_weights = torch.load(load_path)
#         self.net.load_state_dict(torch.load(load_path, map_location={'cuda:0': 'cpu'}))
        
    def train(self, dataloaderDict):
        self.net.to(self.device)
        torch.backends.cudnn.benchmark = True
        for epoch in range(self.num_epochs):
            print('Epochs {}/{}'.format(epoch+1, self.num_epochs))
            for phase in ['train', 'val']:
                if phase == 'train':
                    self.lr_scheduler.step()
                    self.net.train()
                else:
                    self.net.eval()
                    
                epoch_loss = 0.0
                epoch_corrects = 0
                
                if (epoch == 0) and (phase == 'train'):
                    continue
                for inputs, labels in tqdm(dataloaderDict[phase]):
                    inputs, labels = inputs.to(self.device), labels.to(self.device)
                    outputs = self.net(inputs)
                    loss = self.criterion(outputs, labels)
                    _, preds = torch.max(outputs, 1)
                    
                    if phase == 'train':
                        loss.backward()
                        self.optimizer.step()
                        
                    epoch_loss += loss.item() * inputs.size(0)
                    epoch_corrects += torch.sum(preds == labels.data)
                    
                epoch_loss = epoch_loss / len(dataloaderDict[phase].dataset)
                epoch_acc = epoch_corrects.double() / len(dataloaderDict[phase].dataset)
                if( phase=='val') and ( 0.7 < epoch_acc ):
                    self.saveWeight(epoch, epoch_acc)
                    self.bestAcc = epoch_acc
                    print('save weight')
                print('{} Loss: {:.4f} Acc: {:.4f}'.format(phase, epoch_loss, epoch_acc))
                
    def eval(self, imgList, transform):
        
        
        for label in class_index:
            path = './result/'+label
            if not os.path.exists(path):
                os.makedirs(path)
        
        load_path = './weightsFineTuningColor_epoch48_0.724258.pth'
        load_weights = torch.load(load_path)
        print(load_path)
        
        self.net.load_state_dict(load_weights)
        self.net.load_state_dict(torch.load(load_path, map_location={'cuda:0': 'cpu'}))
        self.net.eval()
        
        for _img in imgList:
            img = Image.open(_img)
            img_transformed = transform(img)
            inputs = img_transformed.unsqueeze_(0)
            inputs = inputs.to(self.device)
            out = self.net(inputs)
            img.close()
            print(out)
            maxid = np.argmax(out.cpu().detach().numpy())
            predict_label_name = class_index[maxid]
            print(predict_label_name)
            filename = _img.split('/')[-1]
            shutil.copyfile(_img, './result/'+ predict_label_name+'/'+filename)
            
                
    def saveWeight(self, i, acc):
        save_path = './weightsFineTuningColor_epoch%d_%f.pth'%(i,acc)
        torch.save(self.net.state_dict(), save_path)





 47%|████▋     | 88/187 [00:26<00:09, 10.75it/s]

In [ ]:
resnetTrain = ResNet()
resnetTrain.train(dataloaders_dict)






  0%|          | 0/4 [00:00<?, ?it/s]




100%|██████████| 4/4 [00:00<00:00, 22.17it/s]





  0%|          | 0/187 [00:00<?, ?it/s]

use in device:  cuda:0
4
tensor([1.0000, 1.7000, 1.7000, 8.0000], device='cuda:0')
Epochs 1/50
val Loss: 1.3553 Acc: 0.4160
Epochs 2/50







  1%|          | 1/187 [00:00<00:18,  9.91it/s]




  2%|▏         | 3/187 [00:00<00:18, 10.06it/s]




  3%|▎         | 5/187 [00:00<00:17, 10.24it/s]




  4%|▎         | 7/187 [00:00<00:17, 10.43it/s]




  5%|▍         | 9/187 [00:00<00:16, 10.53it/s]




  6%|▌         | 11/187 [00:01<00:16, 10.55it/s]




  7%|▋         | 13/187 [00:01<00:16, 10.51it/s]




  8%|▊         | 15/187 [00:01<00:16, 10.56it/s]




  9%|▉         | 17/187 [00:01<00:15, 10.67it/s]




 10%|█         | 19/187 [00:01<00:15, 10.75it/s]




 11%|█         | 21/187 [00:01<00:15, 10.67it/s]




 12%|█▏        | 23/187 [00:02<00:15, 10.71it/s]




 13%|█▎        | 25/187 [00:02<00:15, 10.64it/s]




 14%|█▍        | 27/187 [00:02<00:15, 10.43it/s]




 16%|█▌        | 29/187 [00:02<00:15, 10.41it/s]




 17%|█▋        | 31/187 [00:02<00:14, 10.42it/s]




 18%|█▊        | 33/187 [00:03<00:14, 10.48it/s]




 19%|█▊        | 35/187 [00:03<00:14, 10.28it/s]




 20%|█▉        | 37/187 [00:03<00:14, 10.44it/

テスト

In [126]:
class MakeTestDataList():
    
    def __init__(self):
        self.rootpath =  './Test/'
        self.dir = []
        self.datapath = []
        
    def getTest(self):
        for dirpath in glob.glob(self.rootpath+'/*'):
            self.dir.append(dirpath)
            for path in glob.glob(dirpath+'/*.jpg'):
                self.datapath.append(path)
                
        return self.datapath
    

In [127]:
class TestBaseTransform():
    def __init__(self):
        self.size = 256
        self.mean = ((0.5,))
        self.std = ((0.22,))
        self.base_transform = {
            'test':
                transforms.Compose([
                transforms.RandomResizedCrop(self.size, scale=(0.5,1.0)),
                transforms.ToTensor(),
                transforms.Normalize(self.mean, self.std)
                ]),
        }
        
    def __call__(self, img, phase='test'):
        return self.base_transform[phase](img)

In [130]:
resnetTrain = ResNet()
test = MakeTestDataList()
path = test.getTest()
transform = TestBaseTransform()
resnetTrain.eval(path, transform)

use in device:  cuda:0
4
tensor([ 3.,  6.,  4., 23.], device='cuda:0')
./weightsFineTuningColor_epoch48_0.724258.pth
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-30.8573,  -5.3766,  20.8814,  15.3734]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-30.9879,  -5.3840,  20.9388,  15.4543]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-5.1329, -3.9315,  9.5801, -0.5625]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-32.5175,  -5.4171,  21.7864,  16.1716]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-12.6879,  -4.3559,  12.8992,   4.1177]], devi

tensor([[-43.9073,  -6.1097,  26.6146,  23.4576]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-39.2010,  -5.8453,  24.5470,  20.5422]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-17.0442,  -4.5382,  14.7115,   6.8586]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-13.5705,  -4.4048,  13.2858,   4.6649]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-27.3597,  -5.1801,  19.3449,  13.2067]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',

tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-15.7126,  -4.5258,  14.2280,   5.9914]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 2.2001, -3.5031,  6.3317, -5.0941]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-33.5647,  -5.5287,  22.0709,  17.0506]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-27.3927,  -4.9915,  19.0499,  13.3559]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-16.2894,  -4.4399,  14.2891,   6.4288]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 3.3954, -3.4524,  5.8334, -5.8457]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-16.2651,  -4.3568,  14.1456,   6.4690]], device='cuda:0',
 

tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       gr

tensor([[-2143.3940, -1510.6411,  2311.1016,  1343.5974]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-2178.9473, -1593.0729,  2417.1487,  1355.3314]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-3620.5984, -7152.4238,  8628.4658,  2140.7866]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-3537.1567, -8641.3896, 10095.3096,  2078.2900]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-1296.4692,  -731.8000,  1161.3090,   868.4080]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-1893.9727, -1256.1881,  1947.4047,  1203.6404]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-74.4816, -56.4889,  75.0485,  56.0603]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-1

tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       gr

tensor([[-22.5339,  -4.7182,  16.9146,  10.3463]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-92.2056, -34.4616,  60.4308,  66.4441]], device='cuda:0',
       grad_fn=<AddmmBackward>)
金枠あり
tensor([[-51.4468,  -6.5333,  29.9269,  28.1283]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
   

tensor([[-1769.8020, -1125.3378,  1772.9619,  1123.1882]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-1982.3988, -1309.3966,  2038.5676,  1254.1736]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-30.6252,  -5.2571,  20.6064,  15.3017]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-26.9318,  -5.0607,  19.0019,  13.0061]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-4.6504, -3.9044,  9.3681, -0.8614]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-33.3270,  -5.5154,  21.9664,  16.9033]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-32.8974,  -5.4912,  21.7777,  16.6372]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-17.8032,  -4.4011,  14.7529,   7.4504

tensor([[-3690.8916, -5077.5566,  6560.9639,  2205.4412]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-3439.4397, -4333.3604,  5719.1172,  2052.0298]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-2907.4658, -2846.2463,  4005.4153,  1747.7496]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-1544.1406,  -991.7459,  1559.4949,   977.2415]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-2792.9275, -2694.5845,  3806.8052,  1680.1854]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-1245.2664,  -665.3157,  1084.1494,   827.7361]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-1005.2842,  -482.7717,   793.9769,   695.3914]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
ten

tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       gr

tensor([[-29.5774,  -5.2362,  20.2078,  14.6268]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-63.9674,  -7.2366,  35.4276,  35.8846]], device='cuda:0',
       grad_fn=<AddmmBackward>)
金枠あり
tensor([[ 20093.5996, -74713.8984,  77137.6406, -22585.2148]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 105475.0312, -203185.2344,  211617.7344, -114120.7734]],
       device='cuda:0', grad_fn=<AddmmBackward>)
背景あり
tensor([[  88095.1562, -179447.0469,  186386.5625,  -95219.7812]],
       device='cuda:0', grad_fn=<AddmmBackward>)
背景あり
tensor([[  55855.8320, -133708.3438,  138335.1875,  -60615.0781]],
       device='cuda:0', grad_fn=<AddmmBackward>)
背景あり
tensor([[  73108.5938, -158471.6094,  164335.3281,  -79133.1953]],
       device='cuda:0', grad_fn=<AddmmBackward>)
背景あり
tensor([[-6.4393, -4.6409, 10.9774,  0.0632]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-7.0475, -5.6170, 11.5580,  1.0677]], device='cuda:0',
       grad_fn=<AddmmBac

tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-60.6198,  -7.0486,  33.9569,  33.8108]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-54.8040,  -6.5927,  31.1919,  30.2954]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-61.1217,  -6.8998,  33.8898,  34.2415]], device='cuda:0',
 

tensor([[-144.2563,  -51.5065,   95.3912,  100.6309]], device='cuda:0',
       grad_fn=<AddmmBackward>)
金枠あり
tensor([[-189.1586, -106.7560,  145.4789,  150.7518]], device='cuda:0',
       grad_fn=<AddmmBackward>)
金枠あり
tensor([[-102.9062,  -27.4074,   61.8329,   68.6958]], device='cuda:0',
       grad_fn=<AddmmBackward>)
金枠あり
tensor([[-2236.1995, -2112.6875,  3074.6443,  1273.5635]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]]

tensor([[-68.8983,  -7.5136,  37.5938,  38.9392]], device='cuda:0',
       grad_fn=<AddmmBackward>)
金枠あり
tensor([[-26.6027,  -5.0154,  18.8138,  12.8203]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-68.4979,  -7.4911,  37.4179,  38.6912]], device='cuda:0',
       grad_fn=<AddmmBackward>)
金枠あり
tensor([[ 28947.3594, -83519.2500,  86402.6797, -31909.3223]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ -1963.2288, -16825.5488,  18055.8750,    722.3694]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[  61358.2812, -140565.5938,  145775.6250,  -66708.9766]],
       device='cuda:0', grad_fn=<AddmmBackward>)
背景あり
tensor([[ 17152.5664, -69859.1953,  72160.0234, -19516.1250]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[  53038.4414, -129471.1328,  133931.9844,  -57626.9336]],
       device='cuda:0', grad_fn=<AddmmBackward>)
背景あり
tensor([[-559.4213, -260.3531,  447.5130,  373.1103]], device='cuda:0',
       grad_fn=<Addm

tensor([[-6.5509, -3.8573,  9.9530,  0.4200]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-17.3633,  -4.5185,  14.7905,   7.0818]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-14.3683,  -4.4503,  13.6374,   5.1587]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-30.6321,  -5.3640,  20.7825,  15.2338]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 0.5086, -3.6070,  7.0893, -4.0522]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 1.0300, -3.5853,  6.8726, -4.3803]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       gr

tensor([[-23.8013,  -4.9802,  17.7816,  11.0023]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       

tensor([[-784.7167, -410.7051,  666.4391,  530.0662]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-9.6944, -4.1878, 11.5840,  2.2633]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-1.7095, -3.7218,  8.0478, -2.6715]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-31.4996,  -5.4127,  21.1636,  15.7713]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-19.0404,  -4.7128,  15.6900,   8.0530]], device='cuda:0',
 

tensor([[-1635.2399, -1014.7756,  1597.8318,  1053.3584]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-2117.7197, -1517.3068,  2318.5869,  1317.0144]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-1330.4060,  -755.2910,  1196.9235,   890.2308]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-1132.0284,  -618.0541,   978.8852,   772.6437]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-1015.9196,  -546.3774,   870.5912,   693.0408]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-25.8537,  -5.0955,  18.6832,  12.2737]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-28.7942,  -5.2607,  19.9751,  14.0953]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-29.4042, 

tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-3149.1477, -3665.5928,  4918.4766,  1894.9796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-2204.3245, -1603.8444,  2442.0999,  1366.5856]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-1244.3892,  -688.3127,  1095.7676,   838.3651]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-1061.6012,  -569.9366,   912.2062,   720.7030]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-927.6415, -488.7341,  788.3580,  629.2602]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-1069.9260,  -571.0534,   913.4771,   728.8487]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-1355.96

tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       gr

コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-36.4610,  -5.6914,  23.3433,  18.8448]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-17.8912,  -4.6115,  15.1255,   7.3659]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-21.2778,  -4.8195,  16.6421,   9.4518]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-26.6404,  -5.1397,  19.0288,  12.7610]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-12.4195,  -4.3408,  12.7813,   3.9514]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-13.6583,  -4.3723,  13.2635,   4.7447]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-87.6524, -30.2272,  61.2354,  56.7767]], dev

tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       gr

tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       gr

tensor([[-916.7680, -458.8900,  732.3970,  644.4109]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-1607.0306,  -964.4008,  1508.8756,  1063.6122]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-929.8394, -435.2881,  713.2565,  653.0226]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-25.4665,  -4.7215,  17.7329,  12.4897]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-24.7197,  -4.5769,  17.4458,  11.8790]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-35.6895,  -5.3585,  22.5337,  18.5627]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-44.7833,  -6.1589,  26.9995,  24.0004]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-31.1183,  -5.2180,  20.7145,  15.

tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       gr

tensor([[-25.9327,  -5.1000,  18.7180,  12.3227]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       

tensor([[  35937.1953, -101821.7422,  105236.0781,  -39448.4375]],
       device='cuda:0', grad_fn=<AddmmBackward>)
背景あり
tensor([[ 26004.7500, -86148.1797,  88972.2734, -28908.5859]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-213.3246, -115.1931,  175.6514,  153.2717]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-196.0827,  -46.2643,  118.4332,  124.3011]], device='cuda:0',
       grad_fn=<AddmmBackward>)
金枠あり
tensor([[-521.1418, -251.5103,  430.8437,  342.6041]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-241.5901,  -76.6687,  162.8208,  155.8365]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-48.3766,  -6.3608,  28.5781,  26.2263]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.131

tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-57.9371,  -6.8343,  32.6750,  32.1919]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-16.5612,  -4.3143,  14.1796,   6.6925]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-64.1823, -14.9068,  41.3033,  37.8915]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-63.6491,  -7.2188,  35.2877,  35.6874]], device='cuda:0',
       grad_fn=<AddmmBackward>)
金枠あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 17099.7559, -70190.0859,  72511.5703, -19484.2305]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-3304.7781, -9944.2041, 11465.6699,  1776.7931]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 23328.6660, -79598.6094,  82272.8750, -26076.2109]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 31804.5918, -9515

tensor([[-948.2687, -462.0862,  747.0984,  664.4688]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-669.9711, -313.1783,  517.0167,  466.9881]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-583.9829, -264.2361,  442.2115,  406.7996]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-39.7982, -17.8156,  31.3055,  26.3682]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-41.0985, -14.2001,  26.0711,  29.2653]], device='cuda:0',
       grad_fn=<AddmmBackward>)
金枠あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-20.4606,  -4.3805,  15.6443,   9.2115]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-485.8330, -245.8214,  396.7941,  335.53

tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-26.8013,  -5.7507,  18.8804,  13.7071]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-283.5082, -102.3644,  195.9303,  190.3480]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-55.8047,  -6.7781,  31.8415,  30.8280]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-43.4937,  -6.0865,  26.4329,  23.2014]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-78.0188,  -8.0260,  41.6007,  44.5893]], device='cuda:0',
       grad_fn=<AddmmBackward>)
金枠あり
tensor([[  69690.8828, -153586.7031,  159203.9219,  -75463.

tensor([[-37.0238,  -5.7230,  23.5905,  19.1934]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-54.6267,  -6.6884,  31.2858,  30.1141]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[  74423.3828, -160416.4688,  166378.1875,  -80548.1875]],
       device='cuda:0', grad_fn=<AddmmBackward>)
背景あり
tensor([[  84562.7656, -174700.3594,  181412.2812,  -91454.3203]],
       device='cuda:0', grad_fn=<AddmmBackward>)
背景あり
tensor([[  95241.2266, -189454.8750,  197021.1250, -103004.4297]],
       device='cuda:0', grad_fn=<AddmmBackward>)
背景あり
tensor([[ 104137.1016, -201505.5938,  209842.9375, -112685.7344]],
       device='cuda:0', grad_fn=<AddmmBackward>)
背景あり
tensor([[  67690.1562, -150017.0156,  155638.2188,  -73462.4453]],
       device='cuda:0', grad_fn=<AddmmBackward>)
背景あり
tensor([[-1012.4490,  -723.7590,  1136.7885,   599.7589]], device='cuda:0',
      

tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-67.6041,  -7.4409,  37.0253,  38.1375]], device='cuda:0',
       grad_fn=<AddmmBackward>)
金枠あり
tensor([[-25.4170,  -4.9485,  18.2923,  12.0860]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-40.7257,  -5.9310,  25.2169,  21.4867]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-46.6637,  -6.2635,  27.8239,  25.1659]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-53.7391,  -6.6620,  30.9340,  29.5483]], device='cuda:0

tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 6.7985, -3.2612,  4.3383, -7.9539]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       gr

tensor([[-10.2039,  -4.2164,  11.8079,   2.5789]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-19.3395,  -4.6557,  15.7013,   8.2882]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-4.2532, -3.8821,  9.1936, -1.1075]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-20.6063,  -4.8007,  16.3779,   9.0230]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-25.2654,  -5.0461,  18.3981,  11.9204]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-36.8033,  -5.6272,  23.3582,  19.1132]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-9.4802, -4.0189, 11.2351,  2.2367]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-45.4845,  -6.1983,  27.3076,  24.4347]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
 

tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       gr

tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       gr

tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-24.2382,  -5.0048,  17.9735,  11.2729]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       

コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ -3620.2056, -10025.7266,  11536.6533,   2103.3359]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ -3409.5654, -11487.3604,  12963.3799,   1926.4064]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ -2653.6582, -15608.2881,  16975.3867,   1276.0044]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ -2876.6167, -14824.1143,  16241.8350,   1449.0474]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ -2050.0164, -21223.3398,  22631.8945,    626.5396]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ -2256.4177, -20055.8008,  21465.9629,    832.3869]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-3431.8877, -4884.6182,  6274.6909,  2039.5466]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-2742.2966, -2507.7026,  3590.8281,  1658.6461]], device='cuda:0',

tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       gr

tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-961.6736, -548.1514,  860.7683,  649.9745]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-1233.6655,  -743.6744,  1156.7913,   821.4869]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-178.4449,  -82.6507,  142.9221,  118.4436]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-530.6050, -280.2591,  444.2057,  367.4822

コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
  

tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       gr

tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       gr

tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-67.7076, -15.6324,  38.7902,  44.6687]], device='cuda:0',
       grad_fn=<AddmmBackward>)
金枠あり
tensor([[-23.4533,  -4.8835,  17.8853,  10.4502]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-27.9089,  -5.2110,  19.5861,  13.5469]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-18.3966,  -5.3866,  15.6993,   8.0759]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-47.3910,  -6.2395,  28.0466,  25.6516]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-2.8487, -3.8032,  8.5765, -1.9776]], device='cuda:0',

背景あり
tensor([[-319.0580, -139.9860,  242.8793,  216.6699]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0'

tensor([[  92007.3906, -184959.3438,  192259.9844,  -99499.7344]],
       device='cuda:0', grad_fn=<AddmmBackward>)
背景あり
tensor([[  99625.9531, -195496.6719,  203432.2969, -107765.6641]],
       device='cuda:0', grad_fn=<AddmmBackward>)
背景あり
tensor([[ 104810.6172, -202403.1875,  210797.3438, -113417.0938]],
       device='cuda:0', grad_fn=<AddmmBackward>)
背景あり
tensor([[  47703.2031, -119135.6406,  123401.3516,  -52085.2422]],
       device='cuda:0', grad_fn=<AddmmBackward>)
背景あり
tensor([[ 11938.8662, -58357.1094,  60357.3477, -13990.1172]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-1482.3466, -1021.1368,  1608.4976,   895.5424]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-575.3500, -236.1968,  419.0789,  393.2777]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-348.6842, -159.0156,  266.8832,  241.3468]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-1201.5280,  -696.5665,  1128.6293,   770.4614]], device='c

tensor([[ 15695.7012, -65172.0039,  67290.6641, -17872.1719]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-240.3833, -111.1361,  177.2035,  174.7012]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-304.5445,  -99.6919,  196.3823,  208.2757]], device='cuda:0',
       grad_fn=<AddmmBackward>)
金枠あり
tensor([[-398.0404, -173.7758,  303.5537,  268.8265]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-497.5237, -262.1469,  418.2059,  342.1667]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-37.5466,  -5.8201,  23.8328,  19.5735]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.752

tensor([[-44.1462,  -6.1231,  26.7196,  23.6057]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 104317.3125, -201719.5625,  210073.9688, -112883.3125]],
       device='cuda:0', grad_fn=<AddmmBackward>)
背景あり
tensor([[ 100171.8594, -195800.4844,  203837.6250, -108413.5391]],
       device='cuda:0', grad_fn=<AddmmBackward>)
背景あり
tensor([[ 22048.4277, -74639.8359,  77080.1016, -24557.1660]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[  42987.9141, -109804.0938,  113638.5391,  -46929.1133]],
       device='cuda:0', grad_fn=<AddmmBackward>)
背景あり
tensor([[ 11691.8369, -60615.8555,  62394.7695, -13523.7598]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-225.8091,  -74.7194,  154.7426,  146.1306]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-559.7426, -288.4024,  471.9229,  376.9961]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-229.9034,  -83.6800,  164.5098,  149.4560]], device='cuda:0',
       g

tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       gr

tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       gr

tensor([[-54.3689,  -6.6974,  31.2107,  29.9385]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[-36.1824,  -7.5102,  20.4723,  23.2562]], device='cuda:0',
       grad_fn=<AddmmBackward>)
金枠あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[-15.1326,  -4.4933,  13.9732,   5.6322]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
       grad_fn=<AddmmBackward>)
コンクリート
tensor([[ 8.1314, -3.1864,  3.7527, -8.7796]], device='cuda:0',
   

tensor([[-999.5334, -557.7105,  876.4336,  682.0587]], device='cuda:0',
       grad_fn=<AddmmBackward>)
背景あり
